### ISSUE TITLE
Missing most properties

### ISSUE THREAD

**Issue by torsten-liermann** [puschie286/fritzbox-bridge#10]
Hi,

I have posted an issue at homey, but so far I have had no response. [description](https://community.athom.com/t/fritzbox-bridge-v0-5-1-beta/11334/16)

I would like to fix the problem myself, but I am not yet familiar with the test environment, nor do I have a plan to try the Firtz! Box API without homey.

Can you help me?

**Comment by puschie286** [comment]
sry for very late response
does this problem still exist ? sounds like a permission problem, did you check the log ?
as long as the login/authentication works the information should be accessible
