### ISSUE TITLE
Failed to load device list

### ISSUE THREAD

**Issue by carmei** [puschie286/fritzbox-bridge#17]
Hi, thanks for the great app. I guess I was able to setup the settings within the app and received the feedback valid login.
When I try to add a device, that means Fritz!Dect 400 or Fritzbox (Cable 6490) I received the error message "Failed to load device list". Not sure if this is an error/issue or if the box itself or the mentioned device is currently not supported. Maybe you can give me some advice. Many thanks.

Carsten

**Comment by puschie286** [comment]
Currently dect 400 is not supported but it’s on my todo list for the next update.
But you shouldn’t get an error when requesting the device list - can you check your Fritzbox if you have enabled the DECT functionality and the used login has the right to gathering smart home information ?

**Comment by carmei** [comment]
Many thanks for your reply. I checked the settings within my FritzBox and the mentioned parameters are enabled. I solved the issue by changing the Url Setting within the app from http://fritz.box to http://192.168.xx.x
