### ISSUE TITLE
Rademacher RolloTron DECT 1213

### ISSUE THREAD

**Issue by dirkg173** [puschie286/fritzbox-bridge#19]
Hi,

is it possible to integrate the RolloTron DECT 1213 from Rademacher?
The RolloTron DECT 1213 is specially designed for the communication with the Fritzbox.

More information can be found on the manufacturer's website:
https://www.rademacher.de/rollladen-sonnenschutz/loesungen/rollotron-dect
https://service.rademacher.de/hc/de/sections/360005190440-RolloTron-DECT-1213

Currently I don't have a RolloTron DECT 1213 yet, but would buy one if it would be integrated in the app. I could also do some tests then.

Best regards,
Dirk

**Comment by puschie286** [comment]
Hi,

ich bin mal so frei auf deutsch zu antworten ( da du deutsche links geschickt hast ^^ )

rein technisch ist das kein Problem, die fritzbox api kann in der aktuellen Version DECT rollläden bedienen.
Allerdings kann ich kein Versprechen dazu machen, wann ich zeitlich zu der Integration komme

MfG Christoph
Von: dirkg173
Gesendet: Sonntag, 21. März 2021 12:07
An: puschie286/fritzbox-bridge
Cc: Subscribed
Betreff: [puschie286/fritzbox-bridge] Rademacher RolloTron DECT 1213 (#19)

Hi,
is it possible to integrate the RolloTron DECT 1213 from Rademacher?
The RolloTron DECT 1213 is specially designed for the communication with the Fritzbox.
More information can be found on the manufacturer's website:
https://www.rademacher.de/rollladen-sonnenschutz/loesungen/rollotron-dect
https://service.rademacher.de/hc/de/sections/360005190440-RolloTron-DECT-1213
Currently I don't have a RolloTron DECT 1213 yet, but would buy one if it would be integrated in the app. I could also do some tests then.
Best regards,
Dirk

**Comment by dirkg173** [comment]
Hi Christoph,

das wäre großartig wenn das klappen würde.
Wenn nötig könnte ich dann auch einen Gurtwickler für Testzwecken zur Verfügung stellen.

Gruß,
Dirk

**Comment by mgallicus** [comment]
Hallo Christoph,

da schließe ich mich dem Dirk an, es wäre in der Tat großartig. Ich habe gerade so ein Teil eingebaut und es funktioniert hervorragend mit der FRITZ!Box. Jetzt würde ich es auch gern noch mit meiner Homey steuern. 

Viele Grüße 
Michael

**Comment by puschie286** [comment]
hey, i know its a long time but im currently working on the implementation - would be great if someone could provide some data to complete the implementation and test it afterwards

**Comment by dirkg173** [comment]
Hallo Christoph,

im Nachhinein habe ich festgestellt, dass sowohl der Lochabstand von dem Mauerkasten für den UP-Gurtwickler als auch der Mauerkasten selber zu klein für den RolloTron DECT 1213 Gurtwickler ist. Deshalb habe ich das Projekt "Elektrischer Gurtwickler" erstmal auf Eis gelegt. Ich kann also keine Daten zur Verfügung stellen.

Gruß,
Dirk

**Comment by puschie286** [comment]
@mgallicus ich bräuchte einmal die geräte daten - diese kannst du ab der v0.9.1 über den "Debug Info" Button in den einstellungen mir zusenden.
In v0.9.2 habe erstmal alles blind implementiert was in der Dokumentation erwähnt wird - wäre gut wenn du schauen könntest was davon funktioniert - falls du noch informationen oder funktionen brauchst, kannst du die auch gerne mit aufleisten, dann schau ich mal was sich davon noch umsetzten lässt

**Comment by mgallicus** [comment]
Hallo Christoph,

jetzt bin ich etwas überfordert: Die Fritzbox Bridge ist bei mir v0.5.8. Dort habe ich gerade einen Diagnosebericht erzeugt (hier der Key: d6930dfa-6a67-43f2-9b2f-600d387fe7ca). Allerdings ist da ja auch der Rademacher Rollotron DECT noch nicht drin. Wahrscheinlich bin ich irgendwie auf dem falschen Dampfer unterwegs, kannst Du mir bitte noch mal weiterhelfen.

Danke und viele Grüße,
Michael

**Comment by puschie286** [comment]
Hey, ja die aktuelle version bisher nur als [test/beta verfügbar](https://homey.app/de-de/app/com.puschie.fritzbox-bridge/Fritzbox-Bridge/test/). vieles ist noch im umbau und alles andere als stabil ^^ daher warte ich noch etwas mit den veröffentlichen der nächsten release version ( diese wird dann auch v1.0.0 sein )

**Comment by mgallicus** [comment]
Hallo Christoph,

So, nun habe ich mal v0.9.3 installiert und getestet. Die zwei guten Nachrichten:
1. Meine bisherigen Außensteckdosen funktionieren noch.
2. Er findet die 3 Rollotrons.

Der Funktionstest ergibt Folgendes:
1. Wenn ich den Rollladen von Hand schließe, dann kann ich ihn mit dem Slider in der App wieder hochfahren.
2. Ich kann ihn nicht nach unten fahren.
3. Ich kann ihn auch beim Nach-oben-fahren nicht auf einen bestimmten Zwischenwert fahren, er fährt immer ganz nach oben.
4. Ganz merkwürdig: Wenn er oben ist und ich den Slider irgendwohin nach unten bewege, zieht er den Gurt noch ein klein wenig straffer. Wenn ich den Slider dann wieder ganz nach oben schiebe, lockert er den Gurt wieder ein klein wenig. Hier stimmt was nicht mit der oberen Begrenzung.
5. Die App bekommt keine Rückmeldung vom Gerät. Wenn ich den Rollladen von Hand fahre, bleibt der Slider wo er ist.
6. Im Grunde bewegt sich der Rollladen immer bis ganz nach oben (falls er dort noch nicht ist), wenn ich am Slider den Wert ändere (egal in welche Richtung).

Ich hoffe Du kannst mit meiner Beschreibung was anfangen. Wenn ich Dir für‘s Debugging noch irgendwas helfen kann, sage bitte Bescheid.

Viele Grüße,
Michael


Am 20.01.2023 um 18:46 schrieb puschie286 ***@***.***>:

﻿

Hey, ja die aktuelle version bisher nur als test/beta verfügbar<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fhomey.app%2Fde-de%2Fapp%2Fcom.puschie.fritzbox-bridge%2FFritzbox-Bridge%2Ftest%2F&data=05%7C01%7C%7C512877de479a4be0acfc08dafb0e511b%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638098336165565653%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=oVbyoCda9bmkbgZeNwMGJYh%2FpLaG6bv0Ld2FFyt%2BZ8k%3D&reserved=0>. vieles ist noch im umbau und alles andere als stabil ^^ daher warte ich noch etwas mit den veröffentlichen der nächsten release version ( diese wird dann auch v1.0.0 sein )

**Comment by puschie286** [comment]
Hi, danke für die Rückmeldung, das werd ich mir mal genauer anschauen. hab auch die daten erhalten, damit sollte ich alles für weitere anpassungen haben :)

**Comment by puschie286** [comment]
mit v0.9.4 sollten der slider den korrekten werd übernehmen.
ich habe die skala der steuerung auch angepasst - bitte überprüfen ob es nun möglich ist spezifische (zwischen) werte einzustellen. Falls das immer noch nicht der fall ist, wäre es super wenn du einen manuell auf ca. 50% stellst und dann mit den debug button mir einmal die werte zukommen lässt, aktuell weis ich leider nicht wie dieser dargestellt werden

**Comment by mgallicus** [comment]
Hallo, der Slider ist weg (siehe Nachricht zum Diagnosebericht). Und hier noch der Key zur Diagnose: dcd92a1e-f8bb-4c25-9fb4-bc5b605072c6. Bezieht sich auf 0.9.5.

Viele Grüße,
Michael


Am 22.01.2023 um 21:07 schrieb puschie286 ***@***.***>:

﻿

mit v0.9.4 sollten der slider den korrekten werd übernehmen.
ich habe die skala der steuerung auch angepasst - bitte überprüfen ob es nun möglich ist spezifische (zwischen) werte einzustellen. Falls das immer noch nicht der fall ist, wäre es super wenn du einen manuell auf ca. 50% stellst und dann mit den debug button mir einmal die werte zukommen lässt, aktuell weis ich leider nicht wie dieser dargestellt werden

**Comment by puschie286** [comment]
danke fürs feedback - habe mit version 0.9.6 noch paar überarbeitung gemacht, jetzt sollte der slider wieder zurück sein ( unter anderen namen ). Es sollten nun auch 3 buttons angezeigt werden für öffnen / schließen / stop. damit ist alles drin, was die daten hergeben - falls es immer noch probleme mit den slider gibt, bitte nochmal eine diagnose schicken ( nachdem der slider benutzt wurde am besten ). danke dir

**Comment by mgallicus** [comment]
Hallo,

also die gute Nachricht: Der Slider ist wieder da. Allerdings zeigt er jetzt das gleiche Fehlerbild, wie ich es bei v0.9.3 beschrieben hatte (fährt nur hoch, nicht runter; komisches Verhalten am oberen Anschlag; Slider zeigt nicht den tatsächlichen Stand). Was mir noch aufgefallen ist: In den Eigenschaften des Geräts kann man für die Statusanzeige "Alarm" konfigurieren - das riecht irgendwie nach einem falschen Gerätetyp. Und einen Stop-Button sehe ich auch nicht, ich habe einen Slider und oben und unten einen Button "ganz auf" bzw. "ganz zu". Ich hoffe, das hilft Dir weiter. Sonst gern wieder melden.


Und der Code aus dem Diagnosebericht (wofür auch immer der ist): 5acf7d58-3e1a-444b-a736-ceb6463f40c4

Viele Grüße,
Michael

**Comment by puschie286** [comment]
hey, also das mit den alarm ist korrekt, das gerät liefert ein alarm zustand an die fritzbox und diesen zeige ich an - für was der benutzt wird kann ich dir leider nicht sagen. 
Könntest du mal schauen, was du für die Rolläden über die Fritzbox selbst steuern kannst ? Mit der neuen Version ( 0.9.7 ) habe ich den Werte-Bereichs des Sliders noch angepasst, aber sonst gibts leider nichts mehr, was man noch anders machen könnte. 
Glaube daher leider das sich das problem mit den anschlag nicht direkt lösen lässt
Die Buttons sollten auf dem Geräte-Details ( wenn du mit dem finger auf dem gerät kurz hälst ) unten bei dem button symbol angezeigt werden.

**Comment by mgallicus** [comment]
Hallo,

also, das sieht ja schon mal viel besser aus. Der Slider-Tab sieht etwas anders aus, den Tab mit den Buttons sehe ich jetzt auch und vor allem: Ich kann die Rollläden hoch *und* runter fahren. Das merkwürdige Ruckeln um den Endpunkt ist auch weg.

Aber es gibt auch noch ein paar offene Probleme (in Reihenfolge der Prio):

  *   Die Geräte lassen sich zwar als Trigger (mit dem Alarm wofürauchimmer) in Flows einbauen, aber nicht als Aktoren - sprich: Ich kann die Rollläden nicht über einen Flow auf oder zu machen.
  *   Der Slider (oder auch die Statusanzeige auf dem Gerätesymbol) aktualisieren nicht den Status (Level) des Geräts.
  *   Für meinen Geschmack funktioniert der Slider genau verkehrt herum, aber okay, entsprechend der Werte auch in der Fritzbox ist es korrekt - 0 % ist offen. Bei meinen anderen Rollläden, die mit Fibaro Shutter UP-Schalter angesteuert werden, habe ich es irgendwie hinbekommen, dass Slider oben auch Rollladen oben bedeutet. Aber wie gesagt, das ist Geschmackssache, da bin ich völlig entspannt.

In der Fritzbox-Oberfläche habe ich einen Slider (der sich auch halbwegs live aktualisiert, wenn das Gerät fährt), und einen Hoch- und einen Runter-Button. Habe hier mal noch einen Screenshot, ich hoffe der kommt über github mit durch:

***@***.***

Und hier wieder der Code aus dem (zweiten) Diagnosebericht von heute Abend: 95ddd4d2-3c5c-4c13-a39e-c90ceb486c84

Viele Grüße,
Michael

**Comment by mgallicus** [comment]
<img width="554" alt="Screenshot 2023-01-28 001229" src="https://user-images.githubusercontent.com/81478309/215223219-65b92667-c4af-49fd-baf4-7bc6d53914cb.png">

**Comment by mgallicus** [comment]
Hallo,
Die Sache mit der Aktualisierung (zweiter Anstrich in der letzten Mail) ist nur auf meine Ungeduld zurückzuführen. Das Aktualisierungsintervall vom Gerät stand standardmäßig auf 60 s, so lange habe ich beim Testen einfach nicht gewartet, sorry. Wenn ich das Intervall verkleinere oder/und entsprechend lange warte, werden Slider und Statusinformationen aktualisiert.

Bleibt tatsächlich nur das Problem mit der Verwendung in Flows, das allerdings ist im Moment noch ein Showstopper.

Viele Grüße,
Michael

**Comment by puschie286** [comment]
hey, mit der neuen version, sollten jetzt auch entsprechende action flow cards zur verüfung stehen

**Comment by mgallicus** [comment]
Hallo, ja, funktioniert gut. Es gibt noch eine kleine Merkwürdigkeit: In dem neuen Universal-Device erscheinen meine drei Rollotrons jeweils doppelt. Jeweils eins hat keine erkennbare Funktionalität (keine Bedienelemente, nix), das jeweils andere funktioniert aber wie gewünscht in der App und in Flows. Danke und Viele Grüße.

**Comment by puschie286** [comment]
sollte mit 0.9.13 gelöst sein, auch gibt es nun eine option um die slider steuerung zu invertieren :)

**Comment by mgallicus** [comment]
Supi, funktioniert. Und danke für’s invertieren 😊
