### ISSUE TITLE
Please add support for FRITZ!DECT 400

### ISSUE THREAD

**Issue by DirkStorck** [puschie286/fritzbox-bridge#31]
Could you please add support for the [FRITZ!DECT 400](https://avm.de/produkte/fritzdect/fritzdect-400/)

Would like to use this switch turn start flows in Homey

**Comment by puschie286** [comment]
hi, sry for late response - im currently at implementing the button types but i still need some data to verify my implementation - do you have one and could send me some data by debug button on settings menu ?

**Comment by DST73** [comment]
Hi, sorry, but I moved on and sold my devices....

**Comment by philDev392** [comment]
Done

**Comment by puschie286** [comment]
@philDev392 thanks for data, added support for dect 440 in 0.9.9 ( buttons + humidity )

**Comment by philDev392** [comment]
@puschie286 cool, thx!

**Comment by philDev392** [comment]
Added DECT400 button to homey and sent new debug info ;-)

**Comment by puschie286** [comment]
@philDev392 
released 0.9.9
dect 440 has trigger card "Button triggered" with button name as parameter. please use auto completion to select the button you want. 
the delay depend on the update frequency ( so if you need faster response, set it to an acceptable timespan )
currently there is no max delay limit and it only detect changes while the app is running

**Comment by philDev392** [comment]
Hab gesehen du kannst auch Deutsch - ist so einfacher:

Beim DECT 440 wird mir (wie beim 400, ist aber da ja korrekt) leider in den Flows nur „Taste ausgelöst“ ohne Variable angezeigt.

Bei beiden Schaltern wird mir beim Auslösen der Fehler „Missing Capability Listener: button.single“ angezeigt.

Am 12.02.2023 um 05:44 schrieb puschie286 ***@***.***>:

﻿

@philDev392<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FphilDev392&data=05%7C01%7C%7C21db19b38a7445dee5c108db0cb3c8f0%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638117738520041854%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=lhIYJeaL2qTi7Y50IE3wsl8fYyHGkASinTMXS1kj0hM%3D&reserved=0>
released 0.9.9
dect 440 has trigger card "Button triggered" with button name as parameter. please use auto completion to select the button you want.
the delay depend on the update frequency ( so if you need faster response, set it to an acceptable timespan )
currently there is no max delay limit and it only detect changes while the app is running

**Comment by puschie286** [comment]
hmm, erstellst du die flows auf dem handy oder den pc ? beim testen ist mir aufgefallen, dass die handy app da etwas probleme macht. ( schau ich mir aber nochmal an )

soweit ich das sehe wird das auslösen der taster von der fritzbox api nicht unterstützt - dafür werd ich leider ohne eigene hardware keine lösung finden können

die taster sollten garnicht im interface angezeigt werden, aber auch dort gibts wohl ein (homey) bug das diese nicht ausgeblendet werden können.

**Comment by philDev392** [comment]
Habe jetzt die Taster gerade entfernt und neu hinzugefügt - jetzt gibt es die Auswahl.
Der 400 funktioniert jetzt genau richtig.
Beim 440 hat es auf Anhieb die Flows nicht ausgelöst, aber da werd ich noch ein bisschen rumprobieren. Liegt vllt auch an mir…
Auslösen der Taster über die App brauch ich gar nicht, stört mich aber auch nicht wenn die Buttons trotzdem dort angezeigt werden.

Vielen vielen Dank dir - melde mich nochmal wenn ich weiß ob alles klappt (weiß nur nicht ob ich heute dazu komme).


Am 12.02.2023 um 13:07 schrieb puschie286 ***@***.***>:

﻿

hmm, erstellst du die flows auf dem handy oder den pc ? beim testen ist mir aufgefallen, dass die handy app da etwas probleme macht. ( schau ich mir aber nochmal an )

soweit ich das sehe wird das auslösen der taster von der fritzbox api nicht unterstützt - dafür werd ich leider ohne eigene hardware keine lösung finden können

die taster sollten garnicht im interface angezeigt werden, aber auch dort gibts wohl ein (homey) bug das diese nicht ausgeblendet werden können.

**Comment by philDev392** [comment]
Seit der Version 0.9.11 findet er beim Erstellen eines Flows nur Tastenvariablen von einem anderen Taster ;-)

**Comment by puschie286** [comment]
konnte ich nachstellen, die zurodnung hat nur beim ersten button geklappt^^
in 0.9.12 behoben

**Comment by philDev392** [comment]
Der DECT 400 funktioniert jetzt (in meinem Szenario) einwandfrei.
Der DECT 440 erkennt leider den Tastendruck nicht und löst somit keine Flows aus. Die Variablen sind jetzt alle da bzw richtig:-)

Mach dir bitte keinen Stress - das sind nur Nice-To-Have Features. Find es eh voll genial, dass du dran weiterschraubst!
Danke dir!

**Comment by puschie286** [comment]
danke für das herausfinden ^^ kannst du mir noch die debug infos für den funktionierenden zustand zukommen lassen ? vlt finde ich noch was, das diesen schritt überflüssig macht - soweit ich das verstehe, kannst du dann diese nicht mehr in der fritzbox verwenden ?

**Comment by philDev392** [comment]
Debug-Info ist gerade raus.
Folgende Konfiguration habe ich jetzt:
1. Die Taster in der Fritzbox hinzugefügt.
2. Alle Taster-Belegungen aus der Fritzbox herausgelöscht (initial sind diese eh leer). Wichtig: Wirklich alle, also auch Heizungssteuerung (Temperatur hoch/runter) oder ähnlichey.
3. Suche Geräte im Homey über Fritzbox Bridge als Universal.
4. Einrichten der Flows in Homey für den jeweiligen Taster/Tastendruck.
5. Fertig :-)

**Comment by philDev392** [comment]
Da die Tastenbelegungen auf Fritzboxseite auf verschiedenen Reitern (Ansichten) innerhalb des Tasters erfolgt gehe ich davon aus, dass entweder die Fritzbox dann das Event über die API nicht auslöst oder es evtl andere interne Tasten-IDs sind (Tasten 1-4 Reiter 1, Tasten 1-4 Reiter 2, Tasten 1-4 Reiter 3)

**Comment by puschie286** [comment]
die übertragenen daten sind wohl die gleichen - da kann ich leider nicht mehr machen, werd die info mal im forum verlinken und den thread schließen. falls neue infos dazu gibt, gerne hier posten oder ein neuen issue aufmachen
