### ISSUE TITLE
plan to update to sdk 3 for homy2023

### ISSUE THREAD

**Issue by tlundi60** [puschie286/fritzbox-bridge#32]
Hello

i like the app , and need because i use a fritzbox with devices

the question
  according to homey, the app does not work on the new homey pro 2023.

Is an update planned?

best regards
Thomas

**Comment by puschie286** [comment]
hi, just checked the changes and it looks like its not that complicated - because there are a few request to add support for new DECT devices and a few points on my personal todo list for this app, im currently checking the scope of this update.

**Comment by tlundi60** [comment]
Hi Thanks for the answer, it would be great if the APP would also run on the new Homey Many thanks in advance, I would also donate something to you! regards Thomas

 

Gesendet: Samstag, 22. Oktober 2022 um 18:03 Uhr
Von: "puschie286" ***@***.***>
An: "puschie286/fritzbox-bridge" ***@***.***>
Cc: "tlundi60" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [puschie286/fritzbox-bridge] plan to update to sdk 3 for homy2023 (Issue #32)


 

hi, just checked the changes and it looks like its not that complicated - because there are a few request to add support for new DECT devices and a few points on my personal todo list for this app, im currently checking the scope of this update.

**Comment by HenkRenting** [comment]
I would really like an update to SDK v3 as well. If you feel like it, there's another community developer that offers help to others (though he is busy yet 😉):
https://community.homey.app/t/app-pro-fritzbox-bridge-v0-5-8-beta/11334/73
And many thanks to you for your work on the app so far! I'd be happy to support you with a beer (or some), when updated..

**Comment by puschie286** [comment]
hi, v3 update is currently in test phase. the full release is planed for this weekend

**Comment by puschie286** [comment]
update is offical available
