### ISSUE TITLE
Add wlan device connected to condition card

### ISSUE THREAD

**Issue by pmolensky** [puschie286/fritzbox-bridge#33]
Is it possible to add the wlan device (dis)connected to the and/or condition cards?

**Comment by puschie286** [comment]
yes, this is possible - i add this on my todo list for the next release ( hopefully at end of this year )

**Comment by puschie286** [comment]
added in 0.9.0 - please let me know if you need more informations ( like which wlan, connection speed or something like that )

**Comment by pmolensky** [comment]
I installed 0.9 test version, but don't see the and/or action card. I've removed and added my router (4790), but no cards.

**Comment by puschie286** [comment]
not sure if this is how it works but you can use them in the logic cards
![grafik](https://user-images.githubusercontent.com/2429036/213037378-79f5f2ec-93ac-4b0e-bb1c-ab92db348455.png)

**Comment by puschie286** [comment]
added condition cards in 0.9.9 ( for ip, mac and name )
