### ISSUE TITLE
Message.ErrorLogin

### ISSUE THREAD

**Issue by A-lex-ande-r** [puschie286/fritzbox-bridge#42]
Hallo, ich bekomme seit dem Wochenende keine Verbindung mehr zur Fritz!Box. Anbei die ID des Diagnoseberichts: c5021d76-e2c9-4131-9da3-f54e0360b4a6. Danke schon mal für den Support.

**Comment by A-lex-ande-r** [comment]
![image](https://github.com/user-attachments/assets/2d75ed04-2b62-45ef-80aa-fd7c2a466ff4)
![image](https://github.com/user-attachments/assets/897b6a13-1e6d-4511-a10b-9c8ebf9116d0)

**Comment by puschie286** [comment]
Hi, versuch mal statt fritz.box die vollständige IP zu nutzten. Kann dir
leider nicht sagen, wie die IPv6 Unterstützung bei Homey ist, daher bitte
mal überprüfen ob Homey eine IPv4 zugewiesen bekommen hat.

(In den Logs ist der Fehler "ENETUNREACH" zu finden, d.h. er kann aus
verschiedenen Gründen die Fritzbox nicht erreichen (DNS-Auflösung schlägt
fehl, Gateway nicht gültig, ungültige Konfiguration). Vieles davon sollte
die App von Homey beziehen bzw nutzten)

MfG
Christoph

Am Di., 8. Okt. 2024 um 10:24 Uhr schrieb A-lex-ande-r <
***@***.***>:

**Comment by A-lex-ande-r** [comment]
Danke für die schnelle Rückmeldung. 
Eintrag von IP Adresse der Fritz!Box und Restart des Homeys hat das Problem behoben :-)
