### ISSUE TITLE
Fritz!Dect 200 device card question

### ISSUE THREAD

**Issue by mvl64** [puschie286/fritzbox-bridge#5]
I'm using FritzDect 200 devices.
Switching works like a charm, so now I can set schedules as well as control from Homey 8D.

I do have a question though: the device cards in Homey show three tick boxes:
1) automatic timer
2) device input locked
3) API input locked  

Are these linked to:
1) device is scheduled by FritzBox (automatic switching & schedule enabled)?
2) Permit manual switching by button on the device (general settings - advanced - manual switching)
3) permit manual switching by telephone, app or user interface

If no, could you kindly explain the purpose of these device settings ?

**Comment by puschie286** [comment]
Hi,
yes your right
1.  fritzbox timerplan enabled
2.  disabled input on device
3.  disabled input on api/ui
[[Ref]](https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/AHA-HTTP-Interface.pdf)

sorry for late response
