### ISSUE TITLE
Feature request: Fritz!Dect 200

### ISSUE THREAD

**Issue by mvl64** [puschie286/fritzbox-bridge#6]
It would be great if you could include an option to get device temperature from this device.
Also, it would be nice if we could get the current power & Energy usage.

Are these part of your roadmap ?

**Comment by puschie286** [comment]
you should be able to add the temperature from your DECT 200 as separated temperature sensor.

"Also, it would be nice if we could get the current power & Energy usage."
what do you mean exactly ? 
if you add your DECT 200 as Plug-Device you should have access to this values
