### ISSUE TITLE
Feature request: presence detection

### ISSUE THREAD

**Issue by enigma2k** [puschie286/fritzbox-bridge#7]
Hi,

Could you please add presence detection to the Fritzbox like it is already possible with the netgear and UniFi app? https://apps.athom.com/app/com.gruijter.netgear

The Fritzbox can automatically forward which devices are logged into the Wifi and see it as being present or not present if you are not in the WLAN. This is much more reliable than geotracking.

I'm already using this feature with Home Assistant and it works very reliable. https://www.home-assistant.io/components/fritz/
I'm not a coder myself but the used code doesn't seem to be long, maybe this can help you: https://github.com/home-assistant/home-assistant/tree/dev/homeassistant/components/fritz

**Comment by puschie286** [comment]
nice - great catch!
was already planing to use the connected devices^^ so this fits perfectly

on the first view, i see the home-assitant use a different connection type for gathering this informations - it will be a bit less reliable in my implementation because of the polling intervall

**Comment by enigma2k** [comment]
you mean that in your implementation the status won't be updated as frequently because the polling interval is higher? or does home assistant use some kind of push instead?

**Comment by puschie286** [comment]
yes - you will a delay of <= Polling time. so i need to test a few things to get a smooth detection

**Comment by enigma2k** [comment]
using push like in home assistant is not possible to make it more instant?

**Comment by puschie286** [comment]
hmm^^ unfortunately not.
but im thinking about implementing the TR-064 protocol ( used by home assistant ), that should make request faster, easier and less overhead -> can lower polling interval with less cost.
( feel very unhappy with the current used protocol^^ )

**Comment by WilcoKakkenberg** [comment]
Can you give an update on presence detection?

**Comment by puschie286** [comment]
tests with TR-064 protocol was good
so im plan to implement it in the new few weeks

**Comment by puschie286** [comment]
sry for late update - private stuff got in my way but the next update contain first version of presence detection
currently the only information i get is the device name - most other informations need the TR-064 protocol but that is not used yet

**Comment by puschie286** [comment]
Implemented in last update
